name: tes_database
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.1
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1
  google_fonts: ^2.1.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  # flutter_svg: ^0.23.0+1
  flutter:
    sdk: flutter

  get: 4.3.8
  image_picker: ^0.8.4+4
  url_strategy: ^0.2.0
  easy_mask: ^2.0.1
  pdf: ^3.6.3
  progressive_image: ^2.0.0
  open_file: ^3.1.0
  url_launcher: ^6.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
